adobe/theblog

head.html
style.css

Fix #3 
Added topic handling and very basic styling, using @kptdobe's `author` branch as starting point.

Topics handling

---

head.html

do not cut off rest after topics

---

head.html
style.css

social links

---

head.html

Product - fix layout and code enhancement

---

head.html

Follow up from @kptdobe's comment in #26

better page type handling

---

README.md

Add links to cached pages

---

head.html

Product extraction is broken

---

head.html
header.md
style.css

add page type to body class

---

scripts.js

since #24, latest posts by author weren't showing up anymore. also, the homepage looks better with 12 latest stories (divides nicely into a number of rows depending on screen estate). also consolidated hit template

tweak query

---

helix-index.yaml

Relax index selector for hero image

---

style.css

Style hero images with caption

---

scripts.js

Currently using an old config.

Use latest index

---

scripts.js

make sure text products and topics always get removed

---

scripts.js
style.css

Fix #68 (and center list of posts horizontally)

add posts to topic

---

scripts.js

PR for #70 
I adjusted the content and remove the & in the file names. I am also adjusting the importer to follow the practice. This is the required code change to filter the `&`.

Topics with & cannot be loaded - remove the &

---

scripts.js

Use smaller hero renditions in post lists

---

scripts.js
style.css

show topic badges

---

scripts.js

Respect i18n folder structure

---

head.html

* Moved to CSS-based AF integration
* Moved kit to adobe.com managed ID
* Added Adobe Clean & Adobe Clean Serif
Resolves: GH-92

GH-92 - Update Adobe Fonts to CSS Integration

---

head.html

GH-103 - Switch IMS to Prod URL

---

head.html

* Added base analytics object
* Added bootstrap script
Resolves: GH-80

GH-80 - Initial Analytics Implementation

---

head.html

GH-80 Remove Target & Make script defer

---

head.html

* Changed impl to POC Launch & Analytics
Resolves: GH-80

GH-80 - OOTB Launch & Analytics Impl

---

head.html
scripts.js

Faster images

---

head.html
scripts.js

feat(search): use algolia light w/o instantsearch and save 300kb

---

.gitignore
head.html
partials/modal/modal.js
partials/regionPicker/dict.de.css
partials/regionPicker/regionPicker.css
partials/regionPicker/regionPicker.html
scripts.js
style.css

Has support for US and DE.
All RegionSelector files are loaded async when the user clicks on the region selector link (html, js, css)
Also cleans unneeded whitespace.

#113 Add Region Selector Modal

---

head.html
scripts.js

ios safari >= 11.0 now supported

Support for ios and desktop safari

---

dict.de.css
scripts.js
style.css

translate from and published on

---

scripts.js

fix(query): ensure author qurey uses quotes

---

scripts.js

Post dates should not be timezone dependent

---

scripts.js
style.css

fix(hit): display gray placeholder if no hero image

---

style.css

fix(nav): temporary workaround (#139)

---

style.css

fix(footer): hide 2nd AdChoices link (#141)

---

fstab.yaml
head.html
partials/regionPicker/regionPicker.html

Fix #137 
**CAUTION** Wait with merging until dependencies in #137 are checked off.

Remove gdrive mountpoint and move onedrive back to /

---

scripts.js

fix(query): use new API key

---

scripts.js

Remove unused FEDS privacy (consent) code

---

helix-query.yaml

fix(query): add include definitions for new layout

---

head.html
scripts.js

feat(ia): respect new folder structure

---

head.html
scripts.js

See https://github.com/adobe/theblog/issues/169#issuecomment-620356081

feat(url): drop publish from outer CDN URL

---

head.html
scripts.js
style.css

feat(social): getsocial integration

---

scripts.js
style.css

PR for #162 
One of the styling issue is that "our" width is smaller than original site. But since UI is being changed, I did not spend to much time on it.

feat(banners): styling and magic for banners

---

scripts.js
style.css

feat(post): enable recommended articles

---

style.css

Fix #196 
Example: https://staging--theblog--adobe.hlx.page/en/drafts/embed-test.html

feat(post): recommended articles, margins, card tweaks

---

scripts.js
style.css

feat(design): card tweaks

---

scripts.js

Enable offline query-result 
Check: https://algolia-trial-expiration--theblog--adobe.hlx.page/

fix(algolia): tmp fix

---

.model/homepage.css
.model/homepage.html
head.html
query-results.json
scripts.js
style.css

Part of #179 
News box on homepage - example content:
```
--- 
Check out our collection of stories to help you stay creative, be resilient, and get inspired. 
[More on COVID-19](https://www.adobe.com/covid-19-response.html)
- [](http://localhost:3000/en/drafts/migrated/2020/04/30/coming-together-advocating-for-inclusion-in-the-covid-19-era.html)
- [](http://localhost:3000/en/drafts/migrated/2020/04/14/using-creativity-to-honorheroes-doing-extraordinary-things-during-covid-19.html)
- [](https://theblog-adobe.hlx.page/en/drafts/migrated/2020/05/05/stronger-together-supporting-indias-communities-amidst-covid-19.html)
```

feat(design): news box on homepage

---

.model/cards.css
.model/homepage.css
.model/topic.css
.model/topic.html
.vscode/launch.json
query-results.json
style.css

Still WIP but looking OK in most viewports:
https://staging--theblog--adobe.hlx.page/en/topics/creativity.html

feat(design): topic page header

---

.model/topic.css
dict.de.css
scripts.js
style.css

Implements #192 (among other things)

feat(design): author page and some overall improvements

---

.model/cards.css
.model/homepage.css
.model/homepage.html
scripts.js
style.css

feat(design): multiple improvements and re-enabled algolia query

---

scripts.js
style/home.css

fix(type): post type detection and css improvements

---

scripts.js

feat(feds): switch to blog nav experience

---

scripts.js

chore: switch nav back to adobe.com

---

scripts.js

feat(feds): use blog specific header and footer

---

scripts/home.js
style/home.css

Remove flickering on homepage and hide standard content by default.

feat(design): homepage tweaks

---

.model/filters.css
.model/filters.html
.model/filters.js

* Initial layout and styling for filtering
* Implements https://github.com/adobe/theblog/issues/193

Filter styles

---

.model/filters.html
head.html
scripts.js
scripts/author.js
scripts/common.js
scripts/filters.js
scripts/home.js
scripts/post.js
scripts/topic.js
style.css
style/filters.css
style/topic.css

Fixes #193 
Fixes #179 
Fixes #246 
I added @rgclayton's filtering UI from #214 to the topic page. Ryan: I had to make some minor adjustments, and some things are still amiss, hence the draft PR. Can you give it another look over? Feel free to commit changes directly to the `staging` branch.
@davidnuescheler clicking Apply will call `applyFilters()` with an array of product names.

feat(filters): add filtering UI on topic page

---

scripts/common.js
scripts/filters.js
style.css
style/filters.css
style/home.css

feat(filters): improved clear(all) behavior

---

scripts.js

Implements https://github.com/adobe/theblog/issues/247

feat(feds): add support for new CMP

---

robots.txt

feat(seo): allow crawlers

---

head.html
scripts/common.js

feat(card): move template from html to js (#262)

---

scripts/common.js
scripts/post.js

feat(category): include child categories on category pages

---

scripts/common.js

fix(category): fixed empty category pages

---

scripts/post.js

fix(author): fix avatar extraction regex

---

scripts/common.js
scripts/filters.js
scripts/post.js
scripts/taxonomy.js
scripts/topic.js

fix(filters): adjust product filters to new taxonomy

---

scripts/post.js
scripts/taxonomy.js

feat(taxonomy): solidify taxonomy code

---

scripts.js
scripts/post.js

feat(article): no relative links

---

google65e751e4b8d5548c.html

feat(seo): add google site verification file

---

head.html
scripts.js

Implements https://github.com/adobe/theblog/issues/247
Please do not merge this PR until the new CMP is deployed to Production.

feat(feds): prepare CMP integration for PROD

---

404.html
scripts.js
scripts/blank.js
style/blank.css

see #298
try it at https://custom-404--theblog--adobe.hlx.page/nothere

feat(404): add simple custom 404 page

---

scripts/common.js

feat(post): exclude articles with future publication date

---

.model/cards.css
.model/filters.css
.model/homepage.css
.model/homepage.html
.model/topic.css
style.css
style/author.css
style/filters.css
style/home.css
style/topic.css

Fix #356 
**Test URLs**
- Homepage: https://card-widths--theblog--adobe.hlx.page/
- Topic page: https://card-widths--theblog--adobe.hlx.page/en/topics/creative-inspiration--trends.html
- Article page: https://card-widths--theblog--adobe.hlx.page/en/drafts/embed-test.html
- Author page: https://card-widths--theblog--adobe.hlx.page/en/authors/adobe-communications-team.html

Card widths

---

scripts.js

Implements #346 - Restrict search results to blogs

feat(feds): Restrict search results to blogs

---

scripts/post.js
style/post.css

fix(post): Social share bar should not overlap the footer on mobile

---

.github/workflows/purge-code.yaml

When a code change is being pushed to master, we want to purge the cached code files to make sure the change is instantly visible.

feat(cd): purge code cache on push to master

---

tools/tagger/index.html

Vertical tagger based on users feedback

feat(tagger): vertical tagger

---

scripts/taxonomy.js

fix(topics): trim the incoming topic names

---

scripts/common.js

Fix #423 
An author name `Jäck Bâtés` will now translate to the folloiwng URL: `/en/authors/jack-bates.html`

feat(post): remove diacritics

---

scripts/common.js
scripts/filters.js

fix(filter): filtering does not show expected results

---

scripts/common.js
scripts/filters.js
style.css
style/filters.css
style/topic.css

Staging PR

---

style/topic.css

feat(topic): sub headings

---

scripts/post.js

Fixes edge cases when no author is there, still show the date and vice versa.
Aslo relaxed the author regex to handle "By" and "by".

feat(post): show date if no author and vice versa

---

scripts/post.js

feat(post): show products as tags

---

scripts/post.js

Fix #293 (replaces #421)
TODO:

feat(post): interlinking

---

scripts/post.js

feat(post): avoid author 404s

---

scripts/taxonomy.js

Localized taxonomy

---

scripts/post.js
scripts/taxonomy.js

feat(post): ability to skip interlinking

---

scripts/common.js

Card filtering

---

scripts/common.js
scripts/topic.js
style/topic.css

Empty topic

---

dict.ko.css
helix-query.yaml

Changes required for the ko version of the site. Translations will come later.

feat(ko): prepare Korean site

---

scripts.js
scripts/common.js
scripts/home.js
scripts/post.js

Fix #468 
- exclude gifs from compression
- optimize image sizes for
- [cards](https://img-opt--theblog--adobe.hlx.page/)
- [post](https://img-opt--theblog--adobe.hlx.page/en/publish/2020/10/20/photoshop-the-worlds-most-advanced-ai-application-for-creatives.html): hero and body images
- [homepage](https://img-opt--theblog--adobe.hlx.page/): news and featured article
- [topic](https://img-opt--theblog--adobe.hlx.page/en/topics/news.html): banner
- [author](https://img-opt--theblog--adobe.hlx.page/en/authors/adobe-communications-team.html): avatars and pictures

feat(imgs): enhanced image optimization

---

scripts.js

feat(feds): Extend OneTrust integration

---

dict.de.css
dict.en.css
dict.ko.css
scripts/common.js
scripts/filters.js
scripts/topic.js
style/filters.css

feat(filters): UI to allow clearing single filters

---

scripts/common.js
tools/tagger/index.html

Linkchecker goodie in the tagger: this will check if the topic page corresponding to each topic (either link computed based on topic name or link defined on the topic itself in the taxonomy document) exists or not and provide a report. To test: http://topic-linkchecker--theblog--adobe.hlx.page/tools/tagger/index.html?checkLinks=true

feat(tagger): topic links checker

---

scripts/common.js

Regression introduced while fixing #490

fix(topic): product topic pages are empty

---

dict.ko.css
scripts.js

In some cases, FEDS requires the country code and not the language. Implemented a simple mapping, assuming we'll have only 2 or 3 mappings to do in the end.

feat(feds): mapping lang to country for feds nav

---

.github/workflows/run-tests.yaml
.vscode/launch.json
scripts/common.js
scripts/filters.js
scripts/home.js
scripts/post.js
scripts/taxonomy.js
test/features/taxonomy/en.json
test/karma.config.js
test/package-lock.json
test/package.json
test/unit/taxonomy.test.js
tools/tagger/index.html

Fix #510 
All changes needed to switch the taxonomy from Word to Excel. Still need some manual testing on the site but things should be close to the end.
Also added our first unit tests for the taxonomy.js file.
Test URL: https://xlsx-taxonomy--theblog--adobe.hlx.page/

Taxonomy based on XSLX file

---

tools/tagger/index.html

Fix #515
Visible here: https://tagger-lang-selector--theblog--adobe.hlx.page/tools/tagger/index.html

feat(tagger): add a language dropdown to the tagger

---

scripts/author.js
tools/sidekick/plugins.js

Instagram is not part of the supported social links.

feat(author): support for Instagram as social link

---

dict.es.css
dict.fr.css
dict.it.css
helix-query.yaml

Index and css strings for the fr/es/it sites. I need them in master, no need to go via staging.

feat(locale): add fr/es/it support

---

scripts/common.js
scripts/home.js

Exclude feature is lost on "load more articles"

fix(home): "load more" loses the filters

---

scripts/common.js
scripts/topic.js
style.css
style/topic.css

Fix #545 
Fix #557 
Test URLs:
- [Topic with different title](https://new-topic-design--theblog--adobe.hlx.page/en/topics/_test.html)
- [Topic with featured article and header image](https://new-topic-design--theblog--adobe.hlx.page/en/topics/_test_featured.html)
- [Topic with featured article and default header](https://new-topic-design--theblog--adobe.hlx.page/en/topics/_test_featured_blank.html)

Topic enhancements

---

.github/workflows/run-tests.yaml
.vscode/launch.json
test/features/interlink/keywords.json
test/features/interlink/static01.html
test/features/interlink/static02.html
test/features/interlink/static03.html
test/integration/post.test.js
test/integration/utils.js
test/package-lock.json
test/package.json

While implementing requested changes to the interlink feature, I thought it would sure be nice to have integration tests 😉  so I looked into adding a simple framework which can easily be extended to IT other features.

test(post): interlink integration tests

---

.github/workflows/run-tests.yaml
.vscode/launch.json
scripts/post.js
style/post.css
test/features/interlink/keywords.json
test/features/interlink/static01.html
test/features/interlink/static02.html
test/features/interlink/static03.html
test/integration/post.test.js
test/integration/utils.js
test/karma.config.js
test/package-lock.json
test/package.json
test/unit/interlinks.test.js

Interlinks limits per page and paragraph

---

dict.br.css
dict.jp.css
helix-query.yaml
scripts.js

Used term "Brasil" since this is not really a language and an exception on how we do the mapping (should be Brazilian Portuguese...).

feat(locale): Brasil and Japanese support

---

helix-query.yaml

fix: change fetch target to hlx.page

---

scripts/common.js

Open https://blog.adobe.com/en/apac.html -> empty page
Check console:
```
Uncaught (in promise) TypeError: r.path.startsWith is not a function
at common.js:379
at Array.forEach (<anonymous>)
at translateTable (common.js:356)
at async fetchArticleIndex (common.js:402)
at async fetchHits (common.js:494)
at async fetchArticles (common.js:565)
at async setupHomepage (home.js:93)
```

fix(common): invalid path exception

---

scripts/post.js
tools/sidekick/plugins.js

fix(sidekick): make work with and without /publish

---

scripts.js

feat(search): Add gnav for search

---

scripts.js
style.css

Removing icon as will be added via Authoring:
https://github.com/adobe/theblog/compare/region-picker...elaineskpt:region-picker-cleanup?expand=1#diff-a4f497b03e4ab40d4c48e2202b81c7854f7c7b75e5fa84a5785c84bea0516115L252
Return the actual Region either from sessionStorage or blog.language
https://github.com/adobe/theblog/compare/region-picker...elaineskpt:region-picker-cleanup?expand=1#diff-a4f497b03e4ab40d4c48e2202b81c7854f7c7b75e5fa84a5785c84bea0516115R261
Selected Locale is based on the return from ActualRegion 
https://github.com/adobe/theblog/compare/region-picker...elaineskpt:region-picker-cleanup?expand=1#diff-a4f497b03e4ab40d4c48e2202b81c7854f7c7b75e5fa84a5785c84bea0516115R261
Changes can be viewed:
https://region-picker-cleanup--theblog--elaineskpt.hlx.page/

Region Picker Clean-Up

---

scripts/post.js

ensure https://vimeo.com links are embeddable via block embeds
fix #590

fix(scripts/post.js): extend support for vimeo

---

style/post.css

fix(twitter): unset max-height

---

scripts/post.js
style/post.css

- extended vimeo support
- no max height for twitter embeds

Embed enhancements

---

dict.br.css
dict.es.css

Applied translations for BR and ES.

feat(i18n): BR and ES resources

---

dict.it.css

feat(ui): IT translations

---

helix-redirects.yaml

feat: test redirects

---

helix-redirects.yaml

adding expected URL patterns for blogs.adobe.com DNS switch.

Blogs redirects

---

tools/sidekick/plugins.js

feat(sidekick): use content-proxy@2.7.0

---

tools/sidekick/plugins.js

Fix #616 
Regression introduced in db73b95ccca32744622c080d1195280e1d4e23a9.

fix(sidekick): preview regression

---

scripts/common.js
style.css

Fix #613  and only load the region picker when it's actually needed.
- before: https://theblog--adobe.hlx.page/en/publish/2019/05/07/adobe-summit-emea-2019.html
- after: https://lazy-region-picker--theblog--adobe.hlx.page/en/publish/2019/05/07/adobe-summit-emea-2019.html

Lazyload region picker

---

scripts/common.js
style.css

Fixes position of region picker dropdown to make links inside it work again.

Region picker fix

---

scripts/post.js

fixes #597 
This also fixes the problem of stacking instagram embeds together; which usually causes problems!
Working:
https://fix-instagram--theblog--adobe.hlx.page/en/drafts/mrosier/block-embed-test.html
vs Impacted: 
https://theblog--adobe.hlx.page/en/drafts/mrosier/block-embed-test.html
Also works in Firefox

fix instagram block embeds

---

helix-redirects.yaml

use cached redirects.json. flush needs currently to be done manually.
(which is not a problem, according to @davidnuescheler )

fix(redirects): use cached redirects document

---

scripts/post.js

fixing caption block oversight

fix: caption block

---

scripts/post.js

youtube block embeds are failing because of stringified url not being searchable for query parameters.
check https://fix-block-embeds--theblog--adobe.hlx.page/en/drafts/mrosier/block-embed-test.html

fix(src/post.js): fix youtube block embed failing

---

helix-redirects.yaml

this is using the patters as specified by Alistair Lee

feat(redirects): redirect adobe connect blogs to new subdomain

---

feeds/jp-3d-ar.xml
feeds/jp-ccdojo.xml
feeds/jp-community.xml
feeds/jp-corporate-news.xml
feeds/jp-design.xml
feeds/jp-digital-document.xml
feeds/jp-digital-transformation.xml
feeds/jp-education.xml
feeds/jp-photography.xml
feeds/jp-stock.xml
feeds/jp-ui-ux.xml
feeds/jp-video-audio.xml

fix(feed): correct JP feeds URLs

---

scripts.js
scripts/common.js
scripts/post.js
tools/sidekick/plugins.js

Display dates on cards and in articles matching the date format of the corresponding language.

feat: display dates in local format

---

scripts/post.js

Lead to japanese pages displaying 9 March 2021 in the browser, although they had a date of 03-10-2021 in the source document.

fix: remove UTC timezone from Date.toLocaleString if input date is already a string

---

scripts/post.js

feat(post): support non-latin author names (#644)

---

sitemap.br.xml
sitemap.de.xml
sitemap.es.xml
sitemap.fr.xml
sitemap.it.xml
sitemap.jp.xml
sitemap.ko.xml
sitemap.xml

chore(sitemap): sitemaps refresh

---

robots.txt

Index pages cannot be indexed since they are excluded...

feat(robots): allow to level pages

---

scripts/post.js

feat(post): support multi-lingual keywords

---

head.html

fix: switch font kit to the one used on adobe.com

---

tools/sidekick/plugins.js

See https://github.com/adobe/helix-pages/pull/858

feat(sidekick): delegate window mangement to browser/user

---

scripts.js

Fix #670 
https://stretched-images--theblog--adobe.hlx.page/

fix(img): do not strech images

---

scripts/promotion.js
scripts/v2/promotion.js

fix: publish promotion should also publish .plain.html

---

scripts/v2/common.js

load all the fonts that were listed in the prior fonts file:
https://blog.adobe.com/hlx_fonts/aaz7dvd.css

fix(fonts): load all fonts

---

scripts/post.js
scripts/v2/post.js

Add support for twitter block embeds! 
Test Page: https://add-twitter--theblog--adobe.hlx.page/en/drafts/mrosier/block-embed-test
Live Page Test: 
https://add-twitter--theblog--adobe.hlx.page/en/publish/2021/05/17/influencers-share-their-experience-from-adobe-summit.html

Add twitter

---

scripts/post.js
scripts/v2/post.js
style/post.css
style/v2/post.css

Fix #684
Broken: https://master--theblog--adobe.hlx.page/en/drafts/rofe/italic-caption-test.html
Fixed: https://caption-fixes--theblog--adobe.hlx.page/en/drafts/rofe/italic-caption-test.html

Caption fixes

---

scripts/v2/common.js

support for older safari versions and other non webp enabled browsers

fix: webp polyfill

---

scripts/v2/common.js

chore: lh v8.0.0

---

scripts/v2/common.js
style/v2/lazy-styles.css
style/v2/post.css
style/v2/style.css

CLS seems to be down significiantly. somhow there is something wrong with font in gnav.

fix: CLS on post page and font revert

---

tools/sidekick/config.js

Reproduction steps:
1. Go to https://theblog--adobe.hlx.page/en/topics/_taxonomy.json
2. Open the sidekick
3. Observe JS error `Cannot read property 'pageType' of undefined`

fix(sidekick): sidekick bombs on json preview

---

tools/sidekick/config.js

- remove override of preview button
- ensure .html extension
- ensure underscore in _taxonomy.json

Sidekick: remove preview override

---

tools/sidekick/config.js

fix(sidekick): attaches .html too eagerly

---

scripts/v2/post.js

slideshare block embed support
https://slideshare-embed--theblog--adobe.hlx.page/en/drafts/jennie/announcing-2021-sundance-ignite-x-adobe-fellows.html

feat: slideshare block embed

---

scripts/v2/filters.js
scripts/v2/topic.js

Fix #701 
Test page: https://fix-duplicate-loading--theblog--adobe.hlx.page/en/topics/video-audio.html

fix: avoid duplicate loading of common.js

---

scripts/v2/post.js

https://invalid-date-check--theblog--adobe.hlx.page/en/drafts/pr-ready-for-publish/amazon-web-services-works-with-adobe-experience-cloud-as-it-reimagines-b2b-marketing.html

chore: better invalid date check

---

scripts/v2/common.js
scripts/v2/post.js

https://external-canonical--theblog--adobe.hlx.page/

feat: support external canonical

---

scripts/martech.js
scripts/v2/scripts.js

enabling microfunnel instrumentation for blog.adobe.com
https://microfunnel--theblog--adobe.hlx.page/en/publish/2021/09/15/adobe-for-all-do-one-thing-today.html?cwv=on

feat: enable microfunnel instrumentation

---

scripts/martech.js

https://end-of-survey--theblog--adobe.hlx.page/

chore: end of survey

---

scripts/v2/scripts.js

remove backtick as it is not supported by old browsers

chore: remove backtick

---

head.html

https://microfunnel--theblog--adobe.hlx.page/
for testing turn off javascript in your browser...
@trieloff, this responds with a `400` from the rum collector...

chore: add noscript

---

scripts/martech.js

Merges https://github.com/adobe/theblog/pull/719 to prod once testing has been done.

Analytics improvements
