adobe/theblog

scripts.js

Fix #61 
#62 didn't quite work because the regexp expected a trailing whitespace after `Products:` and `Topics:`. Now it is optional.

make sure plain text products and topics get removed after processing

---

head.html
robots.txt

From @auniverseaway: Did anyone put in the header tags (and robots.txt) to make sure Google, Baidu, and Bing didn’t start crawling the POC Helix blog site?

block search engines from crawling POC site

---

scripts.js

Fix #97 
Test: the date property for [this post](https://no-future--theblog--davidnuescheler.hlx.page/ms/archive/posts/2020/adobe-character-animator-receives-emmy-award-for-technology-and-engineering.html) has been boosted to the near future in the Algolia index, so it should no longer show up on the [homepage](https://no-future--theblog--davidnuescheler.hlx.page).

skip posts with dates in the future

---

scripts.js
style.css

as described in #155 we would like to influence the order of posts on homepages.
this implementation provides a "pinning" mechanism that keeps a list of explicit posts that are a section with a heading `Featured  Posts` at the top of the search result overriding the default "most recent" order.
here are a couple of things that still need to get done:
more generally, we should probably eventually rewrite this to (a) not work on dom manipulations for deduping and sorting or (b) even better do this in one query as opposed to two queries.

feat(homepage) "featured posts" implementation

---

scripts.js

`helixQuery()` is no longer used, so I thought it would be best to consolidate it with the new `helixMultipleQueries()`

refactor(query): consolidate query functions

---

helix-query.yaml

fix #169 
Adds a property `external-path` that contains the path to a document (without leading slash), where `/publish/` in the document path has been stripped.
Depends on fix to issue: https://github.com/adobe/helix-index-pipelines/issues/199
Verifying on this branch, a request to index:
```
en/publish/creating-adobe-experience-platform-pipeline-with-kafka.html
```
will lead to the following indexed property:
```
"external-path": "en/creating-adobe-experience-platform-pipeline-with-kafka.html"
```

fix(index): provide external path in index

---

head.html
style/post.css

Fix #272 
Headings 2 and 3 look more balanced in different settings now.

feat(design): consolidate heading top margin and disable launch

---

scripts/common.js
scripts/post.js

Fix for #277 #278 
This hides the Non User Facing tags and shows the parent topics of each topics in the page. This requires to fetch the taxonomy document first.

feat(topic): fix the topic handling

---

tools/tagger/index.html

Fix #283 
- adds 4 visually distinct types of tags (Categories, Products, Industries and Internals): colours and titles
- aligned the "copy as text" feature to keep the order and to match
- `Topics:` Categories, Industries and Internals
- `Products:` Products
- allow to deselect a tag from the list of tags (and not only from the selection panel)
- paste a "Topics: / Products: area" copied from a docx / md file: selection is re-applied
- code reformatting

feat(tagger): enhance tagger

---

helix-query.yaml

When no post body, the topics and categories get indexed as teaser which is incorrect. teaser should be empty.

fix(index): do not index teaser if no body

---

style/post.css

fix(post): Show image captions

---

helix-query.yaml

fix #349 
At the same time, only index files that lie in `.../publish/YYYY/MM/DD/...`.

Allow the section containing the author to be in either case

---

tools/tagger/index.html

Looks like the order changed accidentally at some point, which led the indexer to list topics under products if the products list was empty.

fix(tagger): indexer expects topics before products

---

.model/homepage.css
scripts/common.js
style.css
style/home.css

Fix #360 
URL: https://card-focus--theblog--adobe.hlx.page/
@yalagand I tried implementing your feedback: each card has a border while the focus is within, and only topic and title have tabstops.
I couldn't figure out how to change the order so the title would be the first tabstop within the card, but maybe it would be counter-intuitive anyway...

Card focus indicators

---

helix-query.yaml

Exclude documents from the index that are named 'Document.*'

---

helix-redirects.yaml

We are seeing quite a few requests to legacy feed URLs which all 404 now. Let's redirect them to the main feed instead.

feat(feed): set up redirect for wordpress feed URLs

---

scripts.js

Loosely related to #219: in the new article design, images are never wider than 1000px anymore, so defaulting to 2048 in most cases seems overkill. This makes it dependent on the `window.innerWidth` and `window.devicePixelRatio` to load the optimal image for all viewports.

feat(post): optimize image widths

---

style.css

Fix #448 
Restore the "default" styles but without the `.default` class.

fix(styles): restore margins

---

scripts/post.js

Fix #445 
This cover cases:
- author page contains an image with no url (CMO import)
- author page does not have an image at all
In both cases, the default avatar https://hlx.blob.core.windows.net/external/942ea2ad17270c65cda838d52145ec5b26704d41 is shown instead.

fix(post): no avatar support

---

scripts.js

Implements https://github.com/adobe/theblog/issues/477 which sends the FEDS experience name to the search page, so that the Blogs navigation experience is rendered there as well for consistency purposes.

feat(feds): Pass experience name to Search page

---

scripts/common.js

Fix #490 
The filter query is supposed to work like this:
topic AND (product1 OR product2 ...) AND (industry1 OR industry2 ...)
Error reproduction steps:
1. Go to https://blog.adobe.com/en/topics/creativity.html
2. Filter for industry _B2B_
3. See many _B2B_ articles that have nothing to do with _Creativity_ (unexpected)
Test fix:
1. Go to https://filter-query--theblog--adobe.hlx.page/en/topics/creativity.html
2. Filter for industry _B2B_ (wait for a few minutes for all index segements to load) 
3. See 5 articles that are all tagged _Creativity_ and _B2B_ (expected)

fix(filters): correctly combine main topic with user filters

---

scripts/post.js
scripts/taxonomy.js

Allow the topics in the taxonomy document to be links: the link will be used instead of the magic computation we do based on the topic name.

feat(taxonomy): accept and handle links on topics in taxonomy

---

tools/sidekick/plugins.js

and breaks if there are no topics :)

fix(sidekick): card preview uses topics as teaser

---

scripts/common.js
scripts/filters.js
scripts/post.js
scripts/taxonomy.js
test/features/taxonomy/en.json
test/unit/taxonomy.test.js
tools/sidekick/plugins.js
tools/tagger/index.html

A topic and a product can have the same name (e.g. Creative Cloud). This was "almost" supported before the change to the  xlsx spreadsheet. Authors want to have the feature back because the topic and the product serves different purposes (analytics tagging vs non visible topic vs product page).
While fixing the issue, I discover some existing bugs in how we were treating that case before: 
- https://blog.adobe.com/en/topics/creative-cloud.html does not show the correct list of entries (missing Creative Cloud product children)
- http://taxonomy-topic-can-appear-twice--theblog--adobe.hlx.page/en/topics/creative-cloud.html does contain the correct list now.

feat(taxonomy): Taxonomy topic can appear twice

---

tools/sidekick/plugins.js

We're in an intermediate state between old and new sidekick global variable. I added a safeguard to make theblog plugins wotk with both

fix(sidekick): fix smoke tests

---

scripts/common.js
scripts/home.js
scripts/post.js

Fix #521 
PR allows to specify in "home" page (any page which is not under drafts, publish, author or topics I assume) in the last section: 
- `Topics: ` - (same as in articles) list of topics the articles on the page must have to be visible
- `Products: ` - (same as in articles) list of products the articles on the page must have to be visible
- `Exclude: ` - (new) list of topics and / or products which automatically exclude an article to appear on the page.
Exclude is mainly meant to be use on the homepage to exclude the region "Exclusive" articles.
The last section of a landing page could look like this:
```
Topics: Commerce, Trends & Research
Products: Creative Cloud 
Exclude: CMO By Adobe 
```
which means only articles with topics `Commerce` and `Trends & Research` and product …

feat(landingpage): allow to specify topics, products and new exclude

---

dict.de.css
dict.en.css
dict.es.css
dict.fr.css
dict.it.css
dict.ko.css
scripts/filters.js

Fix #533 
Hi @kptdobe @rofe I do not have permissions to add reviewers, but pinging you here
this is the first commit for the i18n issue with Products and industries in filters
there will be some other commits to the PR related to this file https://github.com/adobe/theblog/blob/master/scripts/filters.js#L236
and also to the add the extra class to the other css locales
to remove the category on button title and change the category to be a class instead a id
Please let me know if you have already any comments

GIT-ISSUE-533

---

style/post.css
style/topic.css

Fix #544 
This small change lets authors add a regular text paragraph in the title section directly underneath the heading, which will not be displayed on the page but added to the page's metadata.
Special case topic page: here the first text paragraph after the heading is already reserved for the tagline, so any meta description must be added as the second paragraph underneath. Changing that (e.g. by moving the tagline to an `h2` or `h3`) would be a breaking change which I'm not sure is worth the effort.

feat(post): meta description authoring

---

tools/tagger/index.html

Tags are not visually nice looking in JP and KO. Also the path separator `/` is not visible in JP.
Also slightly increased the font for all languages
Diff:
- new: https://improve-tagger-jp--theblog--adobe.hlx.page/tools/tagger/index.html?lang=jp
- current: https://theblog--adobe.hlx.page/tools/tagger/index.html?lang=jp

fix(tagger): improve readability for JP and KO tags

---

scripts.js

Enhancements for https://github.com/adobe/theblog/issues/419
The actual footer in blogs do not have the region picker button, so I used the acom experience for the test.
Created already a story is to author the footer for blogs based on the XD.   https://jira.corp.adobe.com/browse/MWPW-81134
https://issue-419-enhancement--theblog--elaineskpt.hlx.page/

Region Picker Selection based on SessionStorage

---

robots.txt

Looks like we forgot to explicitly exclude some language folders. Also we want to allow crawlers into /ko/* now.

chore: enable crawling for en, disable rest

---

tools/tagger/index.html

Reduce spacing to allow the `Internals` to fit on smaller screens.

feat(tagger): fit all categories on smaller screens

---

scripts.js

as a quick temporary solution until we got the server sided `301` for some blogs.adobe.com stragglers.

fix: temporary client redirect

---

tools/sidekick/plugins.js

Adjust to https://github.com/adobe/helix-pages/pull/733 (preview and reload button should not both appear on the inner CDN)

feat(sidekick): prepare for preload plugin

---

tools/sidekick/plugins.js

It's currently 00:00 local time of the browser running the code, so it's only correct if run in the US.

feat(sidekick): make sure date in copied article data is pacific morning time

---

scripts.js
scripts/promotion.js
style/promotion.css

Fix #411 and enable publication of promotions
Example: https://promo-preview--theblog--adobe.hlx.page/en/promotions/products/creative-cloud/premiere-pro-user-guide.html

feat(promotion): preview and publish promotions

---

scripts/post.js

Unlike Chrome, Firefox and Safari don't like `new Date('03-01-2021')`. They prefer `new Date('03/01/2021')`

fix(post): author and date not displayed in firefox and safari

---

scripts/post.js

Fix #643 
Fix #535 
Test: https://issue-643--theblog--adobe.hlx.page/ko/publish/2021/03/15/diversity-survival-strategies.html now links to https://issue-643--theblog--adobe.hlx.page/ko/authors/mary-woo.html which in turn shows all expected articles.

feat(post): support non-latin author names

---

head.html

Authors keep reporting font issues ("umlauts have been bolded in our blog posts", "The special characters in BR Portuguese and Spanish is showing a different font, there is something we can fix?"). The `Adobe Clean` version that we load from the `inq1xob` kit does not seem to contain those special characters. But we also need `Adobe Clean Han Japanese` for JP and `Adobe Clean Han K` for KO.
While we find the way to create the correct kit that contains what we need or we migrate to specific font loading (https://github.com/adobe/theblog/issues/664), this is a temp fix that should solve the font issue. It is a bit dirty because it loads 2 versions of Adobe Clean but it seems to work. Tested on:
- https://fontkit--theblog--adobe.hlx.page/es/publish/2021/04/23/como-crear-una-exitosa-parrilla-d …

fix(font): temp fix - load Adobe Clean version that supports DE, BR, ES and FR

---

tools/sidekick/plugins.js

Publishing spreadhseets directly from Excel currently no longer works with the way we purge via `POST` (CORS). The workaround is to first click preview, then publish from there.

remove publish button from sheets

---

naver2a5f3540429b73b4ab57db9180917416.html

> Our APAC SEO team would like to verify the blog.adobe.com to the Naver webmaster (a similar tool as Google search console, but Korea version), can you please help (or direct me to the right team that can help) adding the verification code file?

chore: add naver webmaster tool verification file

---

scripts/martech.js

testing some core web vitals logging with a sample rate controlled by `weight`
currently set to `1` for testing but i think we should set this probably to `100` when we merge this...

Core Web Vitals logging

---

scripts/martech.js

Sending the data on visibility change is not optimal because the LCP and CLS events might be fired only on page unload, i.e. after the last visibility change - data are then missing, we can observe a lot of empty entries in the logs.
Only viable solution is to send the data when events are fired, which means multiple requests and then multiple log entries. To be able to reconcile the data, I added an id (url hash + timestamp + generated number, probability this is not unique is almost null).
I also added a "page view" entry so that we can observe if the CWV metrics are always persisted or not (might be cases where they are missing). We also get an estimate of the page views (unique ids * 100).
I also added support for `?cwv=on` request parameter so that we can skip the weight computation …

feat(cwv): improve CWV persistence

---

scripts/martech.js

weight must be set to 1 if the `cwv=on` parameter is passed so that we do not mess up the stats.

feat(cwv): if parameter, set weight to 1

---

scripts/v2/post.js

video links for mp4 animations are not being transformed properly
before: https://master--theblog--adobe.hlx.page/en/drafts/jennie/adobe-stock-motion-trend-eye-catching-transformative-transitions.html
after: https://block-animation--theblog--adobe.hlx.page/en/drafts/jennie/adobe-stock-motion-trend-eye-catching-transformative-transitions.html
existing animation blocks do not appear to be impacted by this change: https://block-animation--theblog--adobe.hlx.page/en/publish/2021/08/17/photoshop-releases-major-update-sky-replacement-healing-brush-magic-wand-on-ipad-much-more.html

chore: transform blob video url

---

head.html
scripts/v2/scripts.js

https://microfunnel--theblog--adobe.hlx.page/?rum=on
i had to move the code for the old browser instrumentation into `head.html` .  i am not sure what to do about that but it seems that IE etc. don't even make it through the parsing of `scripts.js` it seems that there is no good path avoid the parsing issues, but if someone has a good idea i am very open to any idea...

microfunnel: update for unsupported browsers

---

scripts/martech.js

Adds additional analytics data 
- `digitalData.page.pageInfo.siteSection: blog.adobe.com`
- `digitalData.page.pageInfo.attributes.pageFilterInfo: "Category: #AdobeForAll | Category: Adobe Life | Product: Photoshop"` (example string, products&categories based on raw topics and products from the source document)
... The [Analytics specification](https://wiki.corp.adobe.com/display/marketingtech/Blogs.adobe.com+-+DataLayer+Specification) mention to add a call to track the `pageload` specifically, but happens automagically already and a second call does nothing.
- [Jira Issue](https://jira.corp.adobe.com/browse/MWPW-97131)
- [Analytics specification](https://wiki.corp.adobe.com/display/marketingtech/Blogs.adobe.com+-+DataLayer+Specification)
Adds additional analytics 
Verified locally that …

feat: add additional analytics
